/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task2;

import java.io.File;
import java.io.IOException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

import org.w3c.dom.Document;
import org.xml.sax.SAXException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    // from https://stackoverflow.com/questions/5059224/which-is-the-best-library-for-xml-parsing-in-java
    public static Document parseDOM(String path) throws ParserConfigurationException, IOException, SAXException {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        DocumentBuilder builder = factory.newDocumentBuilder();
        File file = new File(path);
        return builder.parse(file);
    }

    public static void main(String[] args) throws ParserConfigurationException, IOException, SAXException {
        Document doc = parseDOM("app/src/data.xml");

        // nah cuz im not going to learn like 5 libraries for one question during swot week.
        System.out.println("// nah cuz im not going to learn like 5 libraries for one question during swot week.");
    }
}
